### ISSUE TITLE
How would I use this?

### ISSUE THREAD

**Issue by outercloudstudio** [revzim/mc-realms#1]
First of all I am not the very good a node.  When I run it in the cmd it says invalid credentials. Where would I add credentials?

**Comment by revzim** [comment]
The credentials are most likely your login to authenticate with the minecraft realms api. I provide 2 straight forward code examples in the README. If you are not familiar with node, I suggest learning more about the language and coming back to try this at another time.

**Comment by ElectricPotato** [comment]
Could we get a code example for the new api?
