### ISSUE TITLE
Outdated API

### ISSUE THREAD

**Issue by TimStewartJ** [revzim/mc-realms#2]
It looks like this package cannot currently obtian the IP and port of a realm. The endpoint for that on the realms API seems to have moved to `/worlds/v1/$ID/join/pc`. This seems like a relatively simple fix of refactoring some of the API interaction. I'd be happy to make a PR if I find the time.

**Comment by revzim** [comment]
> 
> 
> It looks like this package cannot currently obtian the IP and port of a realm. The endpoint for that on the realms API seems to have moved to `/worlds/v1/$ID/join/pc`. This seems like a relatively simple fix of refactoring some of the API interaction. I'd be happy to make a PR if I find the time.

The endpoint you provided `/worlds/v1/$ID/join/pc` is the same endpoint as mc-realms is currently using, so I am not quite sure what your point is.  I also do not use realms any more so I will not be updating this at any time in the near future; however, feel free to clone this repo and update whatever you need.

**Comment by TimStewartJ** [comment]
Sorry, that's completely my bad! I had misread the errors I was getting. Apologies for the mix up. Thanks for the info on the future of this project.
